hCaptcha/hcaptcha-android-sdk

.github/workflows/ci.yml, .gitignore, sdk/build.gradle, sdk/src/main/assets/hcaptcha-form.html
* Closes https://github.com/hCaptcha/hcaptcha-android-sdk/issues/1
* transpiles es6 to es5 
* use ie8 css
=> Enforce consistent overlays

sdk/build.gradle, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java
* Dismisses dialog when impossible to communicate back to the activity
=> Fix challenge recreation when activity gets killed

example-app/build.gradle, example-app/proguard-rules.pro, example-app/src/main/res/layout/activity_main.xml, sdk/build.gradle, sdk/consumer-rules.pro, sdk/proguard-rules.pro, sdk/src/main/assets/hcaptcha-form.html, sdk/src/main/res/drawable/ic_logo.xml
* Adds proguard and consumer rules to prevent obfuscation of json serialized content
* Lint fixes
* Bump version to `1.0.3`
=> R8 minification fix

.github/workflows/ci.yml, build.gradle, sdk/build.gradle, sdk/src/androidTest/assets/hcaptcha-form.html, sdk/src/androidTest/java/com/hcaptcha/sdk/AssertUtil.java, sdk/src/androidTest/java/com/hcaptcha/sdk/HCaptchaDialogFragmentTest.java, sdk/src/main/assets/hcaptcha-form.html, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDebugInfo.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java
- #11
1. I observed that when you are trying to debug unit tests from Android Studio, sometimes it fails with
```
java.lang.RuntimeException: Stub!
at org.json.JSONObject.<init>(JSONObject.java:24)
....
```
Here is a workaround: https://stackoverflow.com/a/23507579/902217
1. The project in Android Studio reports false-positive errors related to `Lombok`'s annotations, I have installed plugin as suggested in https://projectlombok.org/setup/android but errors still present IDK why
1. Some test dependencies were updated, I am sure it should be safe
1. I'm open for suggestions for more tests 
1. CI still not stable I have minimized matrix to keep the one which are most stable
=> Bugfix/refactor android UI tests

CHANGES.md, README.md, example-app/src/main/java/com/hcaptcha/example/MainActivity.java, example-app/src/main/res/layout/activity_main.xml, example-app/src/main/res/values/strings.xml, sdk/build.gradle, sdk/src/androidTest/AndroidManifest.xml, sdk/src/androidTest/assets/hcaptcha-form.html, sdk/src/androidTest/java/com/hcaptcha/sdk/AssertUtil.java, sdk/src/androidTest/java/com/hcaptcha/sdk/HCaptchaDialogFragmentTest.java, sdk/src/androidTest/java/com/hcaptcha/sdk/HCaptchaHeadlessWebViewTest.java, sdk/src/androidTest/java/com/hcaptcha/sdk/HCaptchaStateTestAdapter.java, sdk/src/androidTest/java/com/hcaptcha/sdk/TestActivity.java, sdk/src/main/assets/hcaptcha-form.html, sdk/src/main/java/com/hcaptcha/sdk/HCaptcha.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaConfig.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDebugInfo.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaHeadlessWebView.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaJSInterface.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaStateListener.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaWebViewHelper.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaWebViewProvider.java, sdk/src/main/java/com/hcaptcha/sdk/IHCaptcha.java, sdk/src/main/java/com/hcaptcha/sdk/IHCaptchaVerifier.java, sdk/src/main/java/com/hcaptcha/sdk/tasks/Task.java, sdk/src/test/java/com/hcaptcha/sdk/HCaptchaJSInterfaceTest.java, sdk/src/test/java/com/hcaptcha/sdk/HCaptchaTest.java, sdk/src/test/java/com/hcaptcha/sdk/HCaptchaWebViewHelperTest.java
- #37
- #36
Almost ready, still need to:
=> #37 invisible flow feature

sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java
=> #60 ignore state loss for DialogFrarment on dismis call

.github/workflows/ci.yml, README.md
https://github.com/hCaptcha/hcaptcha-android-sdk/tree/docs/add-target-platform-requirements#readme
=> Add target platform requirements

CHANGES.md, sdk/build.gradle, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java, sdk/src/main/res/layout/hcaptcha_fragment.xml
=> refactor: prevent closing on click on loading container

CHANGES.md, sdk/build.gradle, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java
=> fix: show loading screen until the challenge is open

CHANGES.md, sdk/build.gradle, sdk/src/androidTest/AndroidManifest.xml, sdk/src/androidTest/java/com/hcaptcha/sdk/HCaptchaDialogFragmentTest.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java
Fix for `android.util.AndroidRuntimeException
android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed`
More details https://stackoverflow.com/questions/46278681/android-webkit-webviewfactorymissingwebviewpackageexception-from-android-7-0
=> fix: no webview installed runtime exception

jitpack.yml
=> build(jitpack): use open-jdk 11 during jitpack build #93

CHANGES.md, sdk/build.gradle, sdk/src/androidTest/java/com/hcaptcha/sdk/HCaptchaDialogFragmentTest.java, sdk/src/androidTest/java/com/hcaptcha/sdk/TestActivity.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java
* fixes error: "java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState with DialogFragment"
=> fix(sdk): fragment show when activity is closing

README.md
=> Update README.md to clarify fragment lifecycle

example-app/src/main/java/com/hcaptcha/example/MainActivity.java, example-app/src/main/res/layout/activity_main.xml, example-app/src/main/res/values/strings.xml, sdk/src/androidTest/java/com/hcaptcha/sdk/HCaptchaDialogFragmentTest.java, sdk/src/androidTest/java/com/hcaptcha/sdk/HCaptchaStateTestAdapter.java, sdk/src/androidTest/java/com/hcaptcha/sdk/HCaptchaTest.java, sdk/src/androidTest/java/com/hcaptcha/sdk/HCaptchaTestHtml.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaWebView.java
=> fix(sdk): do not intercept touch input when loading is hidden

sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java, sdk/src/main/java/com/hcaptcha/sdk/tasks/OnOpenListener.java
=> fix(sdk): prevent cancel until ready for interaction

README.md
Based on client's case investigation of `android.os.BadParcelableException` crash
=> docs: Add "Retry Predicate Serialization" paragraph

.github/workflows/ci.yml
Fix for problem with run-on branch https://github.com/hCaptcha/hcaptcha-android-sdk/actions/runs/9951182071/job/27490375009
=> ci: look for sonarqube comment for PR only

CHANGES.md, compose-sdk/build.gradle, sdk/build.gradle
=> chore: upgrade lombok and jackson-databind dependencies #167

.github/workflows/ci.yml, CHANGES.md, benchmark/src/androidTest/java/com/hcaptcha/sdk/TestHCaptchaHtml.java, benchmark/src/androidTest/java/com/hcaptcha/sdk/TestHCaptchaVerifier.java, build.gradle, compose-sdk/build.gradle, compose-sdk/src/main/java/com/hcaptcha/sdk/HCaptchaCompose.kt, compose-sdk/src/main/java/com/hcaptcha/sdk/HCaptchaComposeVerifier.kt, example-compose-app/build.gradle, example-compose-app/src/main/java/com/hcaptcha/example/compose/ComposeActivity.kt, gradle/shared/code-quality.gradle, gradle/shared/html-java-gen.gradle, gradle/shared/size-check.gradle, gradle/wrapper/gradle-wrapper.properties, sdk/build.gradle, sdk/src/main/java/com/hcaptcha/sdk/HCaptcha.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaWebViewHelper.java, sdk/src/main/res/layout/hcaptcha_fragment.xml, sdk/src/test/java/com/hcaptcha/sdk/HCaptchaTest.java, test/src/androidTest/java/com/hcaptcha/sdk/HCaptchaDialogFragmentTest.java, test/src/main/AndroidManifest.xml
This PR moves more work into the setup phase, reducing the time it takes to fetch a token at verify when these steps are split.
=> feat: preload webview

CHANGES.md, compose-sdk/build.gradle, sdk/build.gradle, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java
=> fix: call preloadedWebView in case of incomplete Bundle (#189)

example-compose-app/src/main/java/com/hcaptcha/example/compose/ComposeActivity.kt
Attempt to restructure code to make it:
- more straight forward
- separate HCaptcha logic from control UI
- separate setup/verify logic
=> chore: restructure example-compose-app

CHANGES.md, compose-sdk/build.gradle, example-app/src/main/java/com/hcaptcha/example/MainActivity.java, example-app/src/main/res/layout/activity_main.xml, example-app/src/main/res/values/dimens.xml, example-app/src/main/res/values/strings.xml, example-app/src/main/res/values/styles.xml, sdk/build.gradle, sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java, sdk/src/main/res/layout/hcaptcha_fragment.xml, test/src/androidTest/java/com/hcaptcha/sdk/AssertUtil.java, test/src/androidTest/java/com/hcaptcha/sdk/HCaptchaDialogFragmentTest.java
=> fix: loader dark background
