- CHANGES.md
- README.md
- example-app/build.gradle
- example-app/src/main/AndroidManifest.xml
- example-app/src/main/java/com/hcaptcha/example/MainActivity.java
- example-app/src/main/res/layout/activity_main.xml
- example-app/src/main/res/values/strings.xml
- example-app/src/main/res/values/styles.xml
- sdk/build.gradle
- sdk/src/main/java/com/hcaptcha/sdk/HCaptcha.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java
- sdk/src/test/java/com/hcaptcha/sdk/HCaptchaConfigTest.java
- sdk/src/test/java/com/hcaptcha/sdk/HCaptchaTest.java
Closing https://github.com/hCaptcha/hcaptcha-android-sdk/issues/24 
- Fragment instantiation now happens on `new HCaptcha`
- WebView to use cache before reaching network
- Update sample application
> #24 pre-cache enviroment prior to verifyWithHCaptcha call

- .github/workflows/ci.yml
- GitHub Actions CI doesn't support retry for steps
- We can retry shell scripts but this is not an option for `android-emulator-runner` step
- android-emulator-runner action also doesn't have any input to retry tests
`parallels` should help to retry as part of the script of `android-emulator-runner` step
> Add retry with parallels for UI tests

- CHANGES.md
- README.md
- example-app/src/main/java/com/hcaptcha/example/MainActivity.java
- example-app/src/main/res/layout/activity_main.xml
- example-app/src/main/res/values/strings.xml
- sdk/build.gradle
- sdk/src/androidTest/assets/hcaptcha-form.html
- sdk/src/androidTest/java/com/hcaptcha/sdk/HCaptchaHeadlessWebViewTest.java
- sdk/src/main/assets/hcaptcha-form.html
- sdk/src/main/java/com/hcaptcha/sdk/HCaptcha.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaConfig.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDebugInfo.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaHeadlessWebView.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaJSInterface.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaWebViewHelper.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaWebViewProvider.java
- sdk/src/main/java/com/hcaptcha/sdk/IHCaptcha.java
- sdk/src/main/java/com/hcaptcha/sdk/IHCaptchaVerifier.java
- sdk/src/main/java/com/hcaptcha/sdk/tasks/Task.java
- sdk/src/test/java/com/hcaptcha/sdk/HCaptchaJSInterfaceTest.java
- sdk/src/test/java/com/hcaptcha/sdk/HCaptchaTest.java
- sdk/src/test/java/com/hcaptcha/sdk/HCaptchaWebViewHelperTest.java
- Add IHCaptcha interface (to detect breaking changes)
- Utilize lombok to reduce boilerplate
- Make code more explicit - mostly fix nullables
- Change listener behavior: previously we removed the listeners once callback was utilized, currently we never remove these listeners to simplify logic of "reset on timeout" and multiple consecutive `verifyWithHCaptcha` calls.
- Streamlines the example app
- Streamlines the README
- Adds changelog
- Bumps version 2.3.0
> Consolidate code

- CHANGES.md
- MAINTAINERS.md
- README.md
- example-app/src/main/java/com/hcaptcha/example/MainActivity.java
- gradle/config/checkstyle.xml
- sdk/build.gradle
- sdk/src/main/java/com/hcaptcha/sdk/HCaptcha.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaConfig.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaHeadlessWebView.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaJSInterface.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaLog.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaWebViewHelper.java
- sdk/src/test/java/com/hcaptcha/sdk/HCaptchaJSInterfaceTest.java
- The idea of this PR is to simplify troubleshooting performance issues on the client side
- SDK add new `diagnosticLog` property in `HCaptchaConfig` which enables extra logging
- All potentially sensitive info is removed (i.e. GET params in webview requests)
TODO:
> feat: diagnosticLog config

- .github/workflows/ci.yml
- CHANGES.md
- sdk/build.gradle
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaHeadlessWebView.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaWebView.java
- sdk/src/main/res/layout/hcaptcha_fragment.xml
java.lang.RuntimeException: Probable deadlock detected due to WebView API being called on incorrect thread while the UI thread is blocked
> fix: webview crash on "onCheckIsTextEditor" call

- .github/workflows/ci.yml
- benchmark/build.gradle
- benchmark/src/androidTest/AndroidManifest.xml
- benchmark/src/main/AndroidManifest.xml
- build.gradle
- example-app/build.gradle
- example-app/src/main/AndroidManifest.xml
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- sdk/build.gradle
- sdk/src/androidTest/AndroidManifest.xml
- sdk/src/main/AndroidManifest.xml
Benchmark tests don't run stable on the old `com.android.tools.build:gradle` plugin (` < 4.1.3`). But it works really stable for the new version of the plugin (9 of 9 runs were successful)
I propose updating it because sooner or later we will need to update it anyway.
- Android studio needs to be updated to 2022.2.1 (More details about compatibility here https://developer.android.com/studio/releases#android_gradle_plugin_and_android_studio_compatibility)
- This change should not affect end users. I have compared the last aar from jitpack https://jitpack.io/com/github/hCaptcha/hcaptcha-android-sdk/3.3.5/hcaptcha-android-sdk-3.3.5.aar and `sdk/build/outputs/aar/sdk-release.aar` not significant difference observed
> build(deps): upgrade gradle to 7.2.2

- CHANGES.md
- sdk/build.gradle
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java
> fix(dialog): fixed dim background when checkbox is visible

- .github/workflows/ci.yml
- build.gradle
- Upgrade actions to the latest version (it fixes warning about deprecated set-output command)
- Added pre-commit hook setup to gradle
> fi(ci): warnings

- .github/workflows/ci.yml
* add caching wherever possible
* use official gradle action to cache gradle instead `setup-java`
* more features, better caching
* linting: use `'` for strings 
* example pipeline run: https://github.com/hCaptcha/hcaptcha-android-sdk/actions/runs/3524163872
> feat(ci): cache emulators

- CHANGES.md
- sdk/build.gradle
- sdk/src/androidTest/java/com/hcaptcha/sdk/HCaptchaDialogFragmentTest.java
- sdk/src/main/java/com/hcaptcha/sdk/IHCaptchaRetryPredicate.java
- sdk/src/test/java/com/hcaptcha/sdk/HCaptchaConfigTest.java
- #94 
Affected versions: `>= 3.40`
The issue was introduced in 3.4.0 (https://github.com/hCaptcha/hcaptcha-android-sdk/commit/c636106addc54be20908ab365e45400fa12b4705)
> fix(config): serialization crash

- README.md
- sdk/src/androidTest/java/com/hcaptcha/sdk/HCaptchaDialogFragmentTest.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java
> docs: how to prevent closing challenge upon back press

- CHANGES.md
- MAINTAINERS.md
- README.md
- sdk/build.gradle
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaError.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaException.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaWebViewHelper.java
- test/src/androidTest/java/com/hcaptcha/sdk/HCaptchaWebViewHelperTest.java
Fix for crash 
```
Caused by java.lang.Throwable: A WebView method was called on thread 'ThreadPoolForeg'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {c6be634} called on null, FYI main Looper is Looper (main, tid 2) {c6be634})
at android.webkit.WebView.checkThread(WebView.java:2592)
at android.webkit.WebView.removeJavascriptInterface(WebView.java:1929)
at com.hcaptcha.sdk.HCaptchaWebViewHelper$HCaptchaWebClient.shouldInterceptRequest(SourceFile:26)
at K7.a(chromium-TrichromeWebViewGoogle.apk-stable-443021033:15)
at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(chromium-TrichromeWebViewGoogle.apk-stable-443021033:2)
```
+ new `INSECURE_HTTP_REQUEST_ERROR` introduced
> fix: report insecure request error

- benchmark/src/androidTest/java/com/hcaptcha/sdk/HCaptchaWebViewHelperTest.java
- sdk/build.gradle
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaHeadlessWebView.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaWebView.java
- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaWebViewHelper.java
- sdk/src/test/java/com/hcaptcha/sdk/HCaptchaWebViewHelperTest.java
- test/build.gradle
- test/src/androidTest/java/com/hcaptcha/sdk/HCaptchaWebViewHelperTest.java
If `HCaptcha.reset` is called after verification is finished (doesn't mater successful or not) message below gets printed to logcat by the system:
```
Application attempted to call on a destroyed WebView
java.lang.Throwable
at org.chromium.android_webview.AwContents.s(chromium-TrichromeWebViewGoogle6432.aab-stable-609904333:10)
at com.android.webview.chromium.WebViewChromium.loadUrl(chromium-TrichromeWebViewGoogle6432.aab-stable-609904333:15)
at android.webkit.WebView.loadUrl(WebView.java:743)
at com.hcaptcha.sdk.HCaptchaWebViewHelper.reset(Unknown Source:4)
at com.hcaptcha.sdk.HCaptchaDialogFragment.reset(Unknown Source:4)
at com.hcaptcha.sdk.HCaptcha.reset(Unknown Source:4)
at Hcaptcha.reset$lambda$5(Hcaptcha.kt:112)
at Hcaptcha.$r8$lambda$Z8mwFMXoe_rKDOgMykL8R7w_6Zw(Unknown Source:0) …
```
> fix: calling webView.loadUrl on destroyed WebView

- sdk/consumer-rules.pro
There isn't much benefit in having this in production and removing it reduces the final APK size a bit
UPD:
- -556bytes on sample app apk
- less stress on logcat
> feat: drop diagnostic logs from production code

- sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java
The crash looks like a bug in Android itself. This PR is not to fix the issue but to prevent host app from crashing
Open for discussion, to find a better solution
> fix: handle null internal config in args for HCaptchaDialogFragment

- .github/actions/android-emulator-run/action.yml
- .github/workflows/ci.yml
Caching AVD for Android is a questionable practice due to the complexity of emulator setup and unwanted states that should not be stored between CI runs. As a result, this leads to unstable tests on CI.
We definitely should avoid it for benchmarking, as the environment must be as clean as possible between runs.
> ci: use fresh AVD from benchmark tests

- .github/workflows/ci.yml
- benchmark/src/androidTest/java/com/hcaptcha/sdk/HCaptchaWebViewHelperTest.java
- gradle/shared/html-java-gen.gradle
- gradle/shared/size-check.gradle
- sdk/build.gradle
- split large `sdk/build.gradle` to several dedicated scripts for size check and java generation
> refactor: build gradle

- .github/actions/android-emulator-run/action.yml
- .github/actions/check-user-permission/action.yml
- .github/workflows/ci.yml
- benchmark/src/androidTest/java/com/hcaptcha/sdk/HCaptchaWebViewHelperTest.java
- gradle/shared/html-java-gen.gradle
- gradle/shared/size-check.gradle
- sdk/build.gradle
- #109 
https://github.com/hCaptcha/hcaptcha-android-sdk/pull/111 PR looks too complex and hard to maintain. I propose alternative solution for the same problem
> ci: skip sonarqube step for PR from form #109

- CHANGES.md
- compose-sdk/build.gradle
- compose-sdk/src/main/java/com/hcaptcha/sdk/HCaptchaCompose.kt
- example-compose-app/src/main/java/com/hcaptcha/example/compose/ComposeActivity.kt
- sdk/build.gradle
- test/src/androidTest/java/com/hcaptcha/sdk/compose/HCaptchaComposeTest.kt
Fix for broken hideDialog=true for hcaptcha jetpack compose sdk
> fix: compose passive sitekey

- sdk/build.gradle
Jackson 2.14 will require Android SDK 26 so downgrading back to 2.13.x
Related: https://github.com/hCaptcha/hcaptcha-android-sdk/issues/170
> fix: build.gradle downgrade to 2.13.5
